### PR TITLE
Tag Error Catch

### PR DESCRIPTION
**Pull request by N3mines**
Added check to see if index 'tags' exists before calling it

### CODE REVIEW

**Comment by dylanmcreynolds** [comment]
Please add a unit test for this in https://github.com/als-computing/splash-ml/blob/master/tagging/test/test_tag_service.py.  The test will add a tag for for a document where doc['tags']  exists and is none, then tests that the new tag is added to the document after add_tags is run.

**Comment by N3mines** [comment]
Updated the unit tests and all pytests run

**Comment by dylanmcreynolds** [comment]
tests are failing in CI...can you comment out the failing grpahql test (code there isn't ready anyway) and see if we can get it to run succeed at github?

**Comment by N3mines** [comment]
will do

**Comment by N3mines** [comment]
All checks are up and running now, should be good to go :)

**Pull request merged**
